language: ruby # don't install any environment
#sudo: required
branches:
  only:
    - main
rvm:
- 2.2
sudo: required
env:
  global:
  - SOURCE_BRANCH: "main"
  - TARGET_BRANCH: "gh-pages"
  - VPN_LINK: "https://sslvpn.asu.edu/CACHE/stc/3/binaries/anyconnect-linux64-4.4.01054-core-vpn-webdeploy-k9.sh"

#before_install:

install:
  - gem install jekyll
  - gem list
  - sudo apt-get update -qq
  - sudo apt-get install python python-pip python-pil -y 
#  - pip install PIL

before_script:
  - chmod +rx compile.sh
  - cd _data_source
  - python process.py
  - cd ../

script:
  - bash ./compile.sh

after_script:
  - openssl aes-256-cbc -K $encrypted_7aa9289c3b13_key -iv $encrypted_7aa9289c3b13_iv -in asu.enc -out asu -d
  - wget $VPN_LINK
#  - chmod +rx anyconnect-linux64-4.4.01054-core-vpn-webdeploy-k9.sh
#  - sudo ./anyconnect-linux64-4.4.01054-core-vpn-webdeploy-k9.sh
#  - cat ~/asu | /opt/cisco/anyconnect/bin/vpn -s connect sslvpn.asu.edu
#  - /opt/cisco/anyconnect/bin/vpn disconnect
