language: ruby # don't install any environment
rvm:
- 2.1
sudo: required
env:
  global:
  - SOURCE_BRANCH: "main"
  - TARGET_BRANCH: "gh-pages"

install: 
  - gem install jekyll
  - gem list
  
before_script:
  - chmod +rx compile.sh

script: bash ./compile.sh
