language: ruby # don't install any environment
#sudo: required
branches:
  only:
    - main
rvm:
- 2.1
sudo: required
env:
  global:
  - SOURCE_BRANCH: "main"
  - TARGET_BRANCH: "gh-pages"
  - VPN_LINK: "https://sslvpn.asu.edu/CACHE/stc/3/binaries/anyconnect-linux64-4.4.01054-core-vpn-webdeploy-k9.sh"

before_install:
  - openssl aes-256-cbc -K $encrypted_7aa9289c3b13_key -iv $encrypted_7aa9289c3b13_iv -in asu.enc -out asu -d
  - wget https://sslvpn.asu.edu/CACHE/stc/3/binaries/anyconnect-linux64-4.4.01054-core-vpn-webdeploy-k9.sh
install:
  - bash ./anyconnect-linux64-4.4.01054-core-vpn-webdeploy-k9.sh
  - gem install jekyll
  - gem list

before_script:
  - chmod +rx compile.sh
  - cat ~/asu | /opt/cisco/anyconnect/bin/vpn -s connect sslvpn.asu.edu

script: bash ./compile.sh

after_script:
  - /opt/cisco/anyconnect/bin/vpn disconnect
