language: python,ruby # don't install any environment
dist: trusty

branches:
  only:
    - main

rvm:
- 2.2

python:
  - "3.6"

env:
  global:
  - ENCRYPTION_LABEL: "ef16a336ccfc"
  - COMMIT_AUTHOR_EMAIL: "idealab@asu.edu"
  - SOURCE_BRANCH: "main"
  - TARGET_BRANCH: "gh-pages"

addons:
  apt:
    packages:
      - python3

install:
  - gem install jekyll
  - gem list

before_script:
  - pyenv shell 3.5
  - pip install pyyaml pillow
  - python3 -c 'import sys; print(sys.version_info[:])'
  - chmod +rx _compile.sh
  - chmod +rx _deploy.sh
  - cd _data_source
  - python3 process.py
  - cd ../

script:
  - bash ./_deploy.sh

