address:
  - Address Line 1
  - Address Line 2
  - City, State, AZ 12345

phone: 480-727-1234

email: email@asu.edu

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

base_path: "/asurobotics"
#base_path: ""

kramdown:
  input: GFM
  auto_ids: true
highlighter: rouge

organization_name: ASU Robotics
title: ASU Robotics

menu:
  - name: Faculty
    link: faculty
  - name: Labs
    link: labs
  - name: Courses
    link: courses
  - name: Resources
    link: resources
  - name: Get Involved
    link: get-involved

tags: a,b,c,d
