address:
  - Address Line 1
  - Address Line 2
  - City, State, AZ 12345

phone: 480-727-1234

email: email@asu.edu

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

base_path: "/asurobotics"
#base_path: ""

kramdown:
  input: GFM
  auto_ids: true
highlighter: rouge

organization_name: ASU Robotics
title: ASU Robotics

menu:
  - name: Faculty
    link: faculty
  - name: Labs
    link: labs
  - name: Courses
    link: courses
  - name: Resources
    link: resources
  - name: Get Involved
    link: get-involved

faculty_tags:
  - name: poly
    link: faculty_poly
  - name: tempe
    link: faculty_tempe
  - name: control
    link: control
  - name: design
    link: design
    
faculty:
  - name: Dan Aukes
    image: /assets/images/headshot.jpg
    email: danaukes@asu.edu
    lab_link: http://idealab.asu.edu
    tags: [poly, design]
    description: Dan Aukes works on Design, Manufacturing, and Robotics, building design tools to make making robots easier
  - name: Panos Polygerinos
    image: /assets/images/headshot.png
    email: danaukes@asu.edu
    lab_link: http://idealab.asu.edu
    tags: [tempe, control]
    description: I want to talk about something here and I just want it to be different
  - name: Wenlong Zhang
    image: /assets/images/asu_logo.svg
    email: danaukes@asu.edu
    lab_link: http://idealab.asu.edu
    tags: [tempe, control]
    description: I want to talk about something here and I just want it to be different
  - name: Panos Artemiadis
    image: /assets/images/asu_logo.svg
    email: danaukes@asu.edu
    lab_link: http://idealab.asu.edu
    tags: [tempe, control]
    description: I want to talk about something here and I just want it to be different
  - name: Sara Hohenshelt
    image: /assets/images/asu_logo.svg
    email: danaukes@asu.edu
    lab_link: http://idealab.asu.edu
    tags: [tempe, control]
    description: I want to talk about something here and I just want it to be different
tags: a,b,c,d
